{
 "title": "C# DORA Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environments",
    "label": "Environments",
    "query": {
     "query": "label_values(github_deployments_duration{job=\"golang-dora-exporter\"},environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(github_deployments_total{branch=\"dev\", job=\"dora-metrics\",repo=\"hng_boilerplate_csharp_web\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Time To Recovery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1 / (sum(github_deployments_total{job=\"dora-metrics\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(github_deployments_duration{branch=\"dev\", job=\"dora-metrics\", repo=\"hng_boilerplate_csharp_web\", status=\"failure\"})/sum(github_deployments_total{branch=\"dev\", job=\"dora-metrics\", repo=\"hng_boilerplate_csharp_web\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lead Time for Changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(github_deployments_duration_sum{job=\"dora-metrics\"}) \n/ \nsum(github_deployments_total{job=\"dora-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Frequency",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 1, "y": 16 },
   "targets": [
    {
     "expr": "avg (changes(github_deployments_total{branch=\"dev\", instance=\"localhost:8099\", job=\"dora-metrics\", repo=\"hng_boilerplate_csharp_web\", status=\"success\"}[$__interval]))\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median Lead Time to Change",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "github_deployments_duration{branch=\"dev\", instance=\"localhost:8099\", job=\"dora-metrics\", repo=\"hng_boilerplate_csharp_web\", status=\"success\"}[$__interval]\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Deployment Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Succesful Deployments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_deployments_duration{branch=\"dev\", job=\"dora-metrics\", repo=\"hng_boilerplate_csharp_web\", status=\"success\"}/40",
     "legendFormat": "$environments"
    }
   ]
  },
  {
   "title": "Failed Deployments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_deployments_duration{branch=\"dev\", job=\"dora-metrics\", repo=\"hng_boilerplate_csharp_web\", status=\"failure\"}/40",
     "legendFormat": "$environments"
    }
   ]
  },
  {
   "title": "Successful Deployments Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "github_deployments_duration_sum{branch=\"dev\", job=\"dora-metrics\", repo=\"hng_boilerplate_csharp_web\", status=\"success\"}\n",
     "legendFormat": "$environments"
    }
   ]
  },
  {
   "title": "Failed Deployments Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "github_deployments_duration_sum{branch=\"dev\", job=\"dora-metrics\", repo=\"hng_boilerplate_csharp_web\", status=\"success\"}\n\n",
     "legendFormat": "$environments"
    }
   ]
  }
 ]
}